# This GitHub action can publish assets for release when a tag is created.
# Currently, it's setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).

name: release
on:
  create

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Set up Apache Maven Central
      uses: actions/setup-java@v1
      with: # running setup-java again overwrites the settings.xml
        java-version: 1.8
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME 
        server-password: MAVEN_PASSWORD 
        gpg-private-key:  ${{ secrets.PUBLISH_SIGNING_KEY }} # Value of the GPG private key to import
        gpg-passphrase: GPG_PRIVATE_KEY_PASSPHRASE

    - name: Install Maven
      run: |
        curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
        apt-get update
        apt-get -y install unzip
          unzip -d /usr/share maven.zip
          rm maven.zip
          ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
          echo "M2_HOME=/usr/share/apache-maven-3.6.3" | tee -a /etc/environment
      shell: sh  

    - name: Run tests
      run: make test    
      shell: sh

    - name: Build and Publish package
      run: make deploy
      shell: sh
      env:
        MAVEN_USERNAME: ${{ secrets.PUBLISH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        GPG_PRIVATE_KEY_PASSPHRASE: ${{ secrets.PUBLISH_SIGNING_KEY_PASSPHRASE }}
